// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYGj4fCysJyzJ1636-0HdpiGQA_pUNyTM',
    appId: '1:613167135475:web:f13700bd44c14d3e9f5586',
    messagingSenderId: '613167135475',
    projectId: 'areniq-70560',
    authDomain: 'areniq-70560.firebaseapp.com',
    databaseURL: 'https://areniq-70560-default-rtdb.firebaseio.com',
    storageBucket: 'areniq-70560.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnWldZRhMZnxmLvMDBg9jR132OEzimPYQ',
    appId: '1:613167135475:android:96c76dd65c81310f9f5586',
    messagingSenderId: '613167135475',
    projectId: 'areniq-70560',
    databaseURL: 'https://areniq-70560-default-rtdb.firebaseio.com',
    storageBucket: 'areniq-70560.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzoRk7f3_GZ3IpMx-xf_L7nD3aNCXyHqg',
    appId: '1:613167135475:ios:63d648377a954e1c9f5586',
    messagingSenderId: '613167135475',
    projectId: 'areniq-70560',
    databaseURL: 'https://areniq-70560-default-rtdb.firebaseio.com',
    storageBucket: 'areniq-70560.firebasestorage.app',
    iosBundleId: 'com.example.areniqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzoRk7f3_GZ3IpMx-xf_L7nD3aNCXyHqg',
    appId: '1:613167135475:ios:63d648377a954e1c9f5586',
    messagingSenderId: '613167135475',
    projectId: 'areniq-70560',
    databaseURL: 'https://areniq-70560-default-rtdb.firebaseio.com',
    storageBucket: 'areniq-70560.firebasestorage.app',
    iosBundleId: 'com.example.areniqApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYGj4fCysJyzJ1636-0HdpiGQA_pUNyTM',
    appId: '1:613167135475:web:f38a109f5a6d4ce79f5586',
    messagingSenderId: '613167135475',
    projectId: 'areniq-70560',
    authDomain: 'areniq-70560.firebaseapp.com',
    databaseURL: 'https://areniq-70560-default-rtdb.firebaseio.com',
    storageBucket: 'areniq-70560.firebasestorage.app',
  );
}
