import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'firebase_options.dart'; // ← Generated by flutterfire configure

import 'screens/login_screen.dart';
import 'screens/home_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ==================== LOAD ENV ====================
  await dotenv.load(fileName: "assets/.env"); // Make sure you have a .env file in project root

  // ==================== SUPABASE INITIALIZATION ====================
  await Supabase.initialize(
    url: dotenv.env['SUPABASE_URL'] ?? '',
    anonKey: dotenv.env['SUPABASE_KEY'] ?? '',
  );

  // ==================== FIREBASE INITIALIZATION ====================
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const ArenIQApp());
}

class ArenIQApp extends StatelessWidget {
  const ArenIQApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ArenIQ',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF1565C0), // Deep blue water theme
        ),
        useMaterial3: true,
      ),
      // Decide home based on Supabase session or fallback to login
      home: _getInitialScreen(),
    );
  }

  Widget _getInitialScreen() {
    // Supabase session check
    final supabaseSession = Supabase.instance.client.auth.currentSession;

    // TODO: Later, you can also check FirebaseAuth.instance.currentUser if using OTP login
    if (supabaseSession != null) {
      return const HomeScreen();
    } else {
      return const LoginScreen();
    }
  }
}