import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';           // ← Generated by flutterfire configure

import 'screens/login_screen.dart';
import 'screens/home_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ==================== SUPABASE INITIALIZATION (Existing - Unchanged) ====================
  await Supabase.initialize(
    url: 'abc',       // Replace with your Supabase project URL
    anonKey: 'abc',
  );

  // ==================== FIREBASE INITIALIZATION (NEW - For Phone OTP) ====================
  // Added for Phone Number + OTP authentication
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Supabase client shortcut — use this anywhere in the app
  final supabase = Supabase.instance.client;

  runApp(const ArenIQApp());
}

class ArenIQApp extends StatelessWidget {
  const ArenIQApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ArenIQ',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF1565C0), // Deep blue — water theme
        ),
        useMaterial3: true,
      ),
      // Show home if already logged in via Supabase, otherwise show login
      // Note: Currently using Supabase session check.
      // We will later enhance this to also check Firebase Auth for OTP login.
      home: Supabase.instance.client.auth.currentSession != null
          ? const HomeScreen()
          : const LoginScreen(),
    );
  }
}